import { LevelType } from "@/types/init";

export const GRAMMAR_TOPICS_BY_LEVEL: Record<LevelType, string[]> = {
    A1: [
        "Present simple forms of 'to be' – am/is/are",
        "Present simple – I do, I don't, Do I?",
        "Present continuous – I'm doing, I'm not doing, Are you doing?",
        "Present simple or present continuous?",
        "Have got",
        "Was/were – past simple of 'be'",
        "Past simple – regular/irregular verbs",
        "Past simple – negatives and questions",
        "'Will' and 'shall' – Future",
        "Be going to – plans and predictions",
        "Can, can't – ability, possibility, permission",
        "The imperative – Sit down! Don't talk!",
        "Would you like…? I'd like…",
        "Verbs + to + infinitive and verbs + -ing",
        "A/an, plurals – singular and plural forms",
        "A/an, the, no article – the use of articles in English",
        "A, some, any – countable and uncountable nouns",
        "Much, many, a lot of, a little, a few",
        "This, that, these, those",
        "Possessive adjectives and subject pronouns (I/my, you/your, etc.)",
        "Object pronouns vs subject pronouns – me or I, she or her?",
        "Whose, possessive 's – Whose is this? It's Mike's",
        "There is, there are – there was, there were",
        "There or it",
        "Adjectives – old, interesting, expensive, etc.",
        "Adverbs of manner (slowly) – or adjectives (slow)?",
        "Comparative adjectives – older than, more important than, etc.",
        "Superlative adjectives – the oldest, the most important, etc.",
        "Conjunctions: and, but, or, so, because",
        "At, in, on – prepositions of time",
        "At, in, on – prepositions of place",
        "Next to, under, between, in front of, behind, over, etc.",
        "Questions – word order and question words",
        "Adverbs of frequency with present simple",
        "Basic word order in English"
    ],
    A2: [
        "Present simple vs present continuous",
        "Present perfect – form and use",
        "Present perfect or past simple?",
        "Past simple – Form and use",
        "Past continuous and past simple",
        "Past perfect",
        "Will vs be going to – future",
        "Present continuous for future arrangements",
        "Review of all verb tenses A2",
        "Have to, don't have to, must, mustn't",
        "Should, shouldn't",
        "Might, might not – possibility",
        "Used to, didn't use to – past habits and states",
        "How to use the verb 'go' in English",
        "The different uses of the verb 'get'",
        "'Do' vs 'Make' – What's the difference?",
        "Verbs with two objects",
        "Stative vs dynamic verbs (or non-action vs action verbs)",
        "Phrasal verbs: transitive and intransitive, separable and inseparable",
        "First conditional and future time clauses",
        "Second conditional",
        "Present and past simple passive: be + past participle",
        "Reported speech – indirect speech",
        "Expressing purpose with 'to' and 'for'",
        "Infinitives and gerunds – verb patterns",
        "Subject pronouns, object pronouns, possessive pronouns, possessive adjectives",
        "Something, anything, nothing, etc.",
        "Much, many, little, few, some, any – quantifiers",
        "Too, too much, too many, enough",
        "Defining relative clauses – who, which, that, where",
        "So, neither – so am I, neither do I, etc.",
        "Comparative and superlative adjectives and adverbs",
        "No longer, any longer, anymore",
        "However, although, because, so, and time connectors",
        "Prepositions of movement – along, across, over, etc.",
        "On time vs In time, At the end vs In the end.",
        "Asking questions in English – Question forms",
        "Subject questions, questions with preposition"
    ],
    B1: [
        "Present simple or present continuous",
        "Past simple or present perfect?",
        "Present perfect simple and present perfect continuous",
        "Past simple, past continuous, past perfect",
        "Future forms – will, be going to, present continuous",
        "Review of all verb tenses B1",
        "Have to, must, should – obligation, prohibition, necessity, advice",
        "Had better… it's time",
        "Can, could, be able to – ability and possibility",
        "Modal verbs of deduction – must, might, could, can't",
        "Usually, used to, be used to, get used to",
        "B1 Phrasal verbs 1 – Exercises and explanation",
        "B1 Phrasal verbs 2 – Exercises and explanation",
        "B1 Phrasal verbs 3 – Exercises and explanation",
        "First conditional, future time clauses",
        "Second conditional – unreal situations",
        "First and second conditionals",
        "Third conditional – past unreal situations",
        "Passive verb forms",
        "Active and passive voice",
        "Indirect speech – reported speech",
        "Gerund or infinitive – do, to do, doing",
        "A(n), the, no article",
        "Much, many, a lot, little, few, some, any, no – quantifiers",
        "All, both – quantifiers",
        "Both, either, neither – quantifiers",
        "Reflexive pronouns – myself, yourself",
        "Any, no, none – quantifiers",
        "Another, other, others, the other, the others",
        "Defining and non-defining relative clauses",
        "Question tags – aren't you? don't you?",
        "Comparative and superlative adjectives and adverbs",
        "Compound adjectives with numbers: 'a two-day trip'",
        "-Ed/-ing adjectives – adjectives from verbs",
        "So, such, such a, so much, so many",
        "Clauses of contrast, purpose and reason",
        "Verb + preposition",
        "Adjective + preposition",
        "During, for, while",
        "For, since, from – what's the difference?"
    ],
    "B1+": [
        "Present perfect simple or continuous",
        "Narrative tenses – all past tenses",
        "Future continuous and future perfect",
        "Review of all verb tenses B1-B2",
        "Past modal verbs of deduction",
        "Likely, unlikely, bound, definitely, probably – probability",
        "Used to, be used to, get used to",
        "Would and used to – past habits and repeated actions",
        "Verbs of the senses: look, sound, feel, etc.",
        "Zero and first conditional and future time clauses",
        "Second and third conditionals – unreal conditionals",
        "Wishes and regrets – I wish / if only",
        "The passive voice – all tenses",
        "The passive with reporting verbs – It is said that …",
        "Have something done",
        "Gerund or infinitive – verb patterns",
        "Would rather, would prefer – expressing preference",
        "Reporting verbs – admit doing, refuse to do, etc.",
        "Quantifiers – all, most, both, either, neither, any, no, none",
        "Whatever, whenever, wherever, whoever, however",
        "Auxiliary verbs – different uses",
        "The … the … comparatives",
        "Participles as adjectives (-ed / -ing adjectives)",
        "So, such (a), so much, so many",
        "Adjectives without noun",
        "Adjective order",
        "Already, still, yet – What's the difference?",
        "Pretty, rather, quite, fairly",
        "Clauses of contrast and purpose",
        "Questions – different types",
        "Indirect questions",
        "Position of adverbs and adverb phrases"
    ],
    B2: [
        "Narrative tenses, used to, would",
        "Future forms – expressing future time",
        "Other ways to express future – be about to, be due to, etc.",
        "Future in the past",
        "Modal verbs – permission, obligation, prohibition, necessity",
        "Speculation and deduction – modal verbs and expressions",
        "Verbs of the senses",
        "'Get' – different meanings",
        "Unless, even if, provided, as long as, etc. – other expressions in conditionals",
        "All conditionals – mixed conditionals, alternatives to if, inversion",
        "Mixed conditionals – If I were you, I wouldn't have done it",
        "Wish, rather, if only, it's time – unreal uses of past tenses",
        "Distancing – expressions and passive of reporting verbs",
        "Passive verbs with two objects",
        "Verb + object + infinitive/gerund – verb patterns",
        "Gerunds and infinitives – complex forms",
        "Reflexive and reciprocal pronouns",
        "Generic pronouns – common-gender pronouns",
        "Compound nouns and possessive forms",
        "Possessive 's with time expressions – Two hours' walk",
        "Relative clauses – defining and non-defining",
        "There and it – preparatory subjects",
        "Have – auxiliary or main verb",
        "Ellipsis and substitution",
        "Inversion with negative adverbials – adding emphasis",
        "Clauses of contrast, purpose, reason and result",
        "Discourse markers – linking words",
        "Participle clauses",
        "Cleft sentences – adding emphasis"
    ],
    C1: [
        "Advanced tenses and aspect",
        "Advanced modals and conditionals",
        "Advanced passive constructions",
        "Inversion and emphasis",
        "Complex sentence structures",
        "Academic and formal writing structures",
        "Hedging and boosting language",
        "Advanced conjunctions and prepositions",
        "Cohesion and coherence devices",
        "Subjunctive forms"
    ],
    C2: [
        "Nuanced use of all tense forms",
        "Advanced idiomatic expressions",
        "Subtle distinctions in modal usage",
        "Native-like sentence structure variations",
        "Sophisticated rhetorical devices",
        "Complex grammatical transformations",
        "Advanced stylistic devices",
        "Literary grammatical structures",
        "Cultural references in language",
        "Dialectal and regional grammar variations"
    ]
};

export const Languages: string[] = [
    "Amharic",
    "Arabic",
    "Azerbaijani",
    "Bengali",
    "Bhojpuri",
    "Czech",
    "Dutch",
    "French",
    "German",
    "Greek",
    "Gujarati",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Indonesian",
    "Italian",
    "Japanese",
    "Javanese",
    "Kannada",
    "Korean",
    "Malay",
    "Malayalam",
    "Mandarin Chinese",
    "Marathi",
    "Myanmar (Burmese)",
    "Nepali",
    "Odia (Oriya)",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Sinhala",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tagalog (Filipino)",
    "Tamil",
    "Telugu",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
    "Wu Chinese (Shanghainese)",
    "Yoruba"
  ];