import { LevelType } from "@/types/init";

export const GRAMMAR_TOPICS_BY_LEVEL: Record<LevelType, string[]> = {
  A1: [
    "To be – am, is, are",
    "Subject pronouns",
    "Basic sentence structure",
    "Forming questions – Yes/No and WH-",
    "Imperatives – Sit down!, Don’t talk!",
    "There is / There are",
    "This, that, these, those",
    "Possessive adjectives",
    "Object pronouns",
    "Simple present tense",
    "Present continuous",
    "Can / can't for ability and permission",
    "Have got",
    "Articles – a, an, the",
    "Countable and uncountable nouns – some, any",
    "Prepositions of place and time",
    "Demonstratives",
    "Plurals",
    "Adjectives and basic word order",
    "Adverbs of frequency",
    "Conjunctions – and, but, because",
    "Basic wh- questions",
    "Simple past of 'to be' – was/were",
  ],
  A2: [
    "Simple past – regular and irregular verbs",
    "Past continuous",
    "Future forms – will, going to",
    "Have to, must, mustn’t",
    "Should / shouldn’t",
    "Present perfect (ever/never, just/already/yet)",
    "Comparatives and superlatives",
    "Too / enough",
    "Some / any / no / none",
    "Much / many / a lot / a few / a little",
    "Object and subject pronouns",
    "Possessive pronouns",
    "Infinitives and gerunds",
    "First conditional",
    "Second conditional",
    "Used to",
    "Modal verbs – might, may, can, could",
    "Question formation – subject/object questions",
    "Phrasal verbs – basic",
    "Relative clauses – who, which, where, that",
    "So / neither",
    "Word order – adverbs and time expressions",
    "Prepositions of movement",
    "Reported speech – statements",
  ],
  B1: [
    "Present perfect vs past simple",
    "Present perfect continuous",
    "Past perfect",
    "Future continuous and future perfect",
    "Review of all tenses",
    "Modal verbs – ability, possibility, obligation",
    "First, second, and third conditionals",
    "Mixed conditionals – basic",
    "Wish / If only – present and past",
    "Reported speech – statements and questions",
    "Gerunds and infinitives – verb patterns",
    "Reflexive pronouns",
    "Passive voice – present and past",
    "Relative clauses – defining and non-defining",
    "Question tags",
    "Comparatives and superlatives – advanced forms",
    "Quantifiers – all, both, either, neither, none",
    "Articles – advanced use",
    "So / such, too / enough",
    "Phrasal verbs – intermediate",
    "Adjective + preposition",
    "Verb + preposition",
    "Clauses of purpose, reason, contrast",
  ],
  "B1+": [
    "Narrative tenses – past simple, past perfect, past continuous",
    "Future forms – continuous, perfect, be about to",
    "Modal verbs – deduction, obligation, advice",
    "Passive voice – all tenses",
    "Indirect questions",
    "Mixed conditionals – present and past",
    "Wish / If only – past and present regrets",
    "Causative – have something done",
    "Gerunds and infinitives – advanced",
    "Relative clauses – complex use",
    "Quantifiers – complex structures",
    "The … the … comparatives",
    "So / such – emphasis",
    "Participles as adjectives",
    "Reporting verbs – suggest, recommend, admit",
    "Word order with adverbs",
    "Auxiliary verbs – emphasis, question support",
    "Whatever / wherever / whoever – generalisation",
    "Advanced phrasal verbs",
  ],
  B2: [
    "All conditionals – mixed, real, unreal",
    "Future in the past",
    "Inversion in conditionals and emphasis",
    "Advanced modals – speculation and deduction",
    "Passive forms – reporting, two objects",
    "Cleft sentences – It was John who...",
    "Relative clauses – omission, embedded",
    "Nominalisation",
    "Ellipsis and substitution",
    "Discourse markers – therefore, however, on the other hand",
    "Advanced tense usage – narrative tenses, aspect",
    "Verb patterns – complex infinitive/gerund structures",
    "Reflexive and reciprocal pronouns",
    "Pronoun reference – one/ones, this/that",
    "Verb + object + infinitive/gerund",
    "Compound nouns and possessive structures",
    "Adjective order",
    "Adverbs and adverbial phrases – position and emphasis",
  ],
  C1: [
    "Advanced tense use – aspect and nuance",
    "Inversion for emphasis and style",
    "Advanced passive structures",
    "Subjunctive mood",
    "Complex conditionals and alternatives to 'if'",
    "Nominalisation in academic writing",
    "Hedging and boosting language",
    "Cohesion and coherence – formal writing",
    "Discourse markers – high-level linking",
    "Reported speech – complex reporting",
    "Style and register",
    "Advanced relative clauses and noun clauses",
  ],
  C2: [
    "Native-like fluency with all tenses and aspects",
    "Advanced modal distinctions and nuances",
    "Cleft sentences and fronting",
    "Literary and rhetorical grammar structures",
    "Idiomatic grammar use",
    "Stylistic transformations",
    "Complex nominal and verbal structures",
    "Grammar in cultural and dialectal variation",
    "Grammar for persuasion and argumentation",
    "Ellipsis, substitution, and cohesive devices – mastery level",
  ],
};

export const Languages: string[] = [
  "Amharic",
  "Arabic",
  "Azerbaijani",
  "Bengali",
  "Bhojpuri",
  "Czech",
  "Dutch",
  "French",
  "German",
  "Greek",
  "Gujarati",
  "Hausa",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Indonesian",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Korean",
  "Malay",
  "Malayalam",
  "Mandarin Chinese",
  "Marathi",
  "Myanmar (Burmese)",
  "Nepali",
  "Odia (Oriya)",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Sinhala",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tagalog (Filipino)",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
  "Wu Chinese (Shanghainese)",
  "Yoruba",
];

export type Video = {
  id: string;
  title: string;
  category: string;
  level: "Beginner" | "Intermediate" | "Advanced"; // literal union type
};
export const Videos: Video[] = [
  {
    id: "PaErPyEnDvk",
    title: "What’s Hiding at the Most Solitary Place on Earth? The Deep Sea",
    category: "Science",
    level: "Intermediate",
  },
  {
    id: "5iPH-br_eJQ",
    title: "What if We Nuke a City?",
    category: "Science",
    level: "Intermediate",
  },
  {
    id: "9P6rdqiybaw",
    title: "Wormholes Explained – Breaking Spacetime",
    category: "Science",
    level: "Intermediate",
  },
  {
    id: "YEaSxhcns7Y",
    title: "Where did English come from? - Claire Bowern",
    category: "Language",
    level: "Advanced",
  },
  {
    id: "nDZGL1xsqzs",
    title: "Napoleonic Wars: Battle of Waterloo 1815",
    category: "History",
    level: "Intermediate",
  },
  {
    id: "XqvALkpsfRo",
    title: "Battle of the Somme 1916",
    category: "History",
    level: "Intermediate",
  },

  {
    id: "IDj1OBG5Tpw",
    title: "Harvard negotiator explains how to argue | Dan Shapiro",
    category: "Psychology",
    level: "Intermediate",
  },
  {
    id: "QemWDFuU68U",
    title: "Learning from Failure",
    category: "Psychology",
    level: "Beginner",
  },
  {
    id: "uBbVbqRvqTM",
    title: "The Brilliant Mind of Ada Lovelace",
    category: "Science",
    level: "Intermediate",
  },
  {
    id: "e-or_D-qNqM",
    title: "Don’t chase happiness. Become antifragile",
    category: "Psychology",
    level: "Intermediate",
  },
  {
    id: "iTefkqYQz8g",
    title: "How the body keeps the score on trauma ",
    category: "Psychology",
    level: "Intermediate",
  },
  {
    id: "ydVFqpbIIwA",
    title: "The First Crusade: The Bloody Road to Jerusalem 1/2",
    category: "History",
    level: "Intermediate",
  },
  {
    id: "v_8NtmecHMA",
    title: "The First Crusade: Jerusalem Falls 2/2",
    category: "History",
    level: "Intermediate",
  },
  {
    id: "snn29wkKTi4",
    title: "How the Genius of Marie Curie Killed Her",
    category: "Science",
    level: "Intermediate",
  },
];
